spring:
  application:
    name: api-gateway

#gateway config

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
#            - RedirectTo=302, http://codingshuttle.com
            - name: AuthenticationFilter
              args:
                enabled: true
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
              args:
                enabled: true
        - id: shipping-service
          uri: lb://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shipments/**
          filters:
            - StripPrefix=2
            - name: AuthenticationFilter
              args:
                enabled: true

#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


jwt:
  secretKey: jadhsdhashd89720783u1hughda7sdtadagdgh7gagsd78922asdt87126t7egasgdaksb